# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 02:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import enumchoicefield.fields
import schedule.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0001_initial'),
        ('people', '0001_initial'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtg', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('location', models.CharField(max_length=100)),
                ('type', enumchoicefield.fields.EnumChoiceField(default=schedule.models.CallTypeEnum(1), enum_class=schedule.models.CallTypeEnum, max_length=11)),
                ('callee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='people.Person')),
            ],
        ),
        migrations.CreateModel(
            name='CastMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repetoire', to='people.Artist')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='played_by', to='library.Role')),
            ],
        ),
        migrations.CreateModel(
            name='Choreographer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choreographers', to='people.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conductors', to='people.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Costumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costumer', to='people.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='CrewMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crews', to='people.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='director', to='people.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='LightingDesigner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lighting_designers', to='people.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='company.Company')),
            ],
        ),
        migrations.CreateModel(
            name='SetDesigner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_designers', to='people.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('when', models.DateTimeField()),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='schedule.Production')),
            ],
        ),
        migrations.CreateModel(
            name='StageManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_managers', to='people.Artist')),
                ('show', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stage_manager', to='schedule.Show')),
            ],
        ),
        migrations.AddField(
            model_name='setdesigner',
            name='show',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='set_designer', to='schedule.Show'),
        ),
        migrations.AddField(
            model_name='production',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productions', to='schedule.Season'),
        ),
        migrations.AddField(
            model_name='lightingdesigner',
            name='show',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lighting_designer', to='schedule.Show'),
        ),
        migrations.AddField(
            model_name='director',
            name='show',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='director', to='schedule.Show'),
        ),
        migrations.AddField(
            model_name='crewmember',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew', to='schedule.Show'),
        ),
        migrations.AddField(
            model_name='costumer',
            name='show',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='costumer', to='schedule.Show'),
        ),
        migrations.AddField(
            model_name='conductor',
            name='show',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conductor', to='schedule.Show'),
        ),
        migrations.AddField(
            model_name='choreographer',
            name='show',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='choreographer', to='schedule.Show'),
        ),
        migrations.AddField(
            model_name='castmember',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cast', to='schedule.Show'),
        ),
        migrations.AddField(
            model_name='call',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='schedule.Show'),
        ),
    ]
