# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import enumchoicefield.fields
import talent.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', enumchoicefield.fields.EnumChoiceField(default=talent.models.TalentCategoryEnum(1), enum_class=talent.models.TalentCategoryEnum, max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dancing',
            fields=[
                ('talent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='talent.Talent')),
                ('style', enumchoicefield.fields.EnumChoiceField(default=talent.models.DancingStyleEnum(1), enum_class=talent.models.DancingStyleEnum, max_length=11)),
            ],
            options={
                'abstract': False,
            },
            bases=('talent.talent',),
        ),
        migrations.CreateModel(
            name='Orchestra',
            fields=[
                ('talent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='talent.Talent')),
                ('instrument', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'abstract': False,
            },
            bases=('talent.talent',),
        ),
        migrations.CreateModel(
            name='Singing',
            fields=[
                ('talent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='talent.Talent')),
                ('voice', enumchoicefield.fields.EnumChoiceField(default=talent.models.VoiceTypeEnum(1), enum_class=talent.models.VoiceTypeEnum, max_length=12, verbose_name='Voice Type')),
                ('fach', enumchoicefield.fields.EnumChoiceField(default=talent.models.FachEnum(1), enum_class=talent.models.FachEnum, max_length=11)),
            ],
            options={
                'abstract': False,
            },
            bases=('talent.talent',),
        ),
        migrations.AddField(
            model_name='talent',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_talent.talent_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='orchestra',
            name='talent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifics', to='talent.Talent'),
        ),
    ]
