# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import enumchoicefield.fields
import talent.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', enumchoicefield.fields.EnumChoiceField(default=talent.models.TalentCategoryEnum(1), enum_class=talent.models.TalentCategoryEnum, max_length=12, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dancing',
            fields=[
                ('talent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='talent.Talent')),
                ('style', enumchoicefield.fields.EnumChoiceField(default=talent.models.DancingStyleEnum(1), enum_class=talent.models.DancingStyleEnum, max_length=11)),
            ],
            bases=('talent.talent',),
        ),
        migrations.CreateModel(
            name='Orchestra',
            fields=[
                ('talent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='talent.Talent')),
                ('instrument', models.CharField(blank=True, max_length=40)),
            ],
            bases=('talent.talent',),
        ),
        migrations.CreateModel(
            name='Singing',
            fields=[
                ('talent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='talent.Talent')),
                ('voice', enumchoicefield.fields.EnumChoiceField(default=talent.models.VoiceTypeEnum(1), enum_class=talent.models.VoiceTypeEnum, max_length=12, verbose_name='Voice Type')),
                ('fach', enumchoicefield.fields.EnumChoiceField(default=talent.models.FachEnum(1), enum_class=talent.models.FachEnum, max_length=11)),
            ],
            bases=('talent.talent',),
        ),
    ]
