# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 02:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import enumchoicefield.fields
import talent.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DancingStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Dance Style')),
            ],
        ),
        migrations.CreateModel(
            name='Fach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Fach or style')),
            ],
            options={
                'verbose_name_plural': 'Fachs/Styles (Voice)',
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Instrument Name')),
            ],
        ),
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', enumchoicefield.fields.EnumChoiceField(default=talent.models.TalentCategoryEnum(1), enum_class=talent.models.TalentCategoryEnum, max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Range or Type')),
            ],
            options={
                'verbose_name_plural': 'Vocal Ranges/Types',
            },
        ),
        migrations.CreateModel(
            name='Acting',
            fields=[
                ('talent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='talent.Talent')),
            ],
            options={
                'verbose_name_plural': 'Acting',
            },
            bases=('talent.talent',),
        ),
        migrations.CreateModel(
            name='Dancing',
            fields=[
                ('talent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='talent.Talent')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talent.DancingStyle')),
            ],
            options={
                'verbose_name_plural': 'Dancing',
            },
            bases=('talent.talent',),
        ),
        migrations.CreateModel(
            name='Orchestra',
            fields=[
                ('talent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='talent.Talent')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talent.Instrument')),
            ],
            options={
                'verbose_name_plural': 'Orchestra',
            },
            bases=('talent.talent',),
        ),
        migrations.CreateModel(
            name='Singing',
            fields=[
                ('talent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='talent.Talent')),
                ('fach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='talent.Fach', verbose_name='Fach or Style')),
                ('voice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talent.Voice', verbose_name='Vocal Range or Type')),
            ],
            options={
                'verbose_name_plural': 'Singing',
            },
            bases=('talent.talent',),
        ),
        migrations.AddField(
            model_name='talent',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_talent.talent_set+', to='contenttypes.ContentType'),
        ),
        migrations.AlterUniqueTogether(
            name='singing',
            unique_together=set([('voice', 'fach')]),
        ),
    ]
