# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 02:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Instrument',
            new_name='Orchestra',
        ),
        migrations.RenameField(
            model_name='orchestra',
            old_name='plays',
            new_name='instrument',
        ),
    ]
