# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 01:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('talent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='people.Person')),
                ('agent', models.CharField(blank=True, default='', max_length=60)),
                ('headshot', models.ImageField(blank=True, default=None, null=True, upload_to='')),
            ],
            bases=('people.person',),
        ),
        migrations.AddField(
            model_name='person',
            name='talents',
            field=models.ManyToManyField(to='talent.Talent', verbose_name='talents and skills'),
        ),
    ]
