# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 07:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0002_auto_20170913_0737'),
        ('people', '0001_initial'),
        ('talent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='talents',
            field=models.ManyToManyField(to='talent.Talent', verbose_name='talents and skills'),
        ),
        migrations.AddField(
            model_name='staff',
            name='contact_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='people.ContactData'),
        ),
        migrations.AddField(
            model_name='role',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library.Book'),
        ),
        migrations.AddField(
            model_name='role',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.RoleLevel'),
        ),
        migrations.AddField(
            model_name='artist',
            name='contact_data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='people.ContactData'),
        ),
    ]
