# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 08:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dancer',
            fields=[
                ('talent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='people.Talent')),
                ('style', models.CharField(max_length=100)),
            ],
            bases=('people.talent',),
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='talent',
            name='headshot',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
