# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('talent', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='talents',
            field=models.ManyToManyField(to='talent.Talent', verbose_name='talents and skills'),
        ),
    ]
