# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-14 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20170812_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='agent',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='talent',
            name='headshot',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=b''),
        ),
    ]
