# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20170913_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='contact_data',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='contact_info',
        ),
        migrations.AddField(
            model_name='contactdata',
            name='person',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='people.Person'),
        ),
    ]
