# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20170814_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='headshot',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
